# Generated by Django 5.1.15 on 2026-08-01 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes_app', '0003_leave_management'),
        ('payments', '0002_seed_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='booked', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.OneToOneField(help_text='One slot can contain only one booking — enforced by this being a OneToOneField.', on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='classes_app.slot')),
                ('subscription_deducted_from', models.ForeignKey(blank=True, help_text='Set exactly when a session was deducted for this booking (on mark_attended). revert_attended restores to this specific subscription, not whichever one is currently active, so a renewal between attend and revert can never misattribute the restored session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_deducted', to='payments.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_booking_user_status')],
            },
        ),
    ]
