# Generated by Django 5.1.15 on 2026-08-01 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_change_request'),
        ('classes_app', '0004_generate_initial_slots'),
        ('payments', '0004_paymenttransaction_idx_payment_status_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='idx_booking_created_date'),
        ),
        migrations.AddIndex(
            model_name='bookingchangerequest',
            index=models.Index(fields=['requested_date'], name='idx_change_requested_date'),
        ),
    ]
