# Generated by Django 5.1.15 on 2026-08-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_idx_booking_created_date_and_more'),
        ('classes_app', '0004_generate_initial_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(help_text='One slot can contain only one booking — enforced by this being a OneToOneField.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='classes_app.slot'),
        ),
    ]
