# Generated by Django 5.1.15 on 2026-08-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_slot'),
        ('payments', '0005_payment_currency_inr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended')], default='booked', max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subscription_deducted_from',
            field=models.ForeignKey(blank=True, help_text='Set when a session was deducted for this booking at creation time (create_booking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_deducted', to='payments.usersubscription'),
        ),
    ]
