# Generated by Django 5.1.15 on 2026-08-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_cancelled_at_alter_booking_status_and_more'),
        ('classes_app', '0006_remove_slot_idx_slot_date_booked_and_more'),
        ('instructors', '0002_instructorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Auto-assigned at booking time to whichever instructor (not on leave for this slot) currently has the fewest upcoming assigned bookings — see services.assign_instructor. An admin can reassign it afterward; null means no instructor was available to assign (e.g. zero instructor accounts exist).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='instructors.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(help_text='One slot can hold multiple bookings, up to Slot.capacity.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='classes_app.slot'),
        ),
    ]
