# Generated by Django 5.1.15 on 2026-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('transfer_request', 'Transfer Request'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('reschedule_request', 'Reschedule Request'), ('reschedule_approved', 'Reschedule Approved'), ('reschedule_rejected', 'Reschedule Rejected'), ('subscription_purchased', 'Subscription Purchased'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expired', 'Subscription Expired'), ('subscription_low_usage', 'Subscription Low Usage'), ('payment_successful', 'Payment Successful')], max_length=32),
        ),
    ]
