# Generated by Django 5.1.15 on 2026-08-05 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_timetableconfig_break_end_time_and_more'),
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_leaves_created', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='instructors.instructorprofile')),
                ('slots', models.ManyToManyField(blank=True, help_text='Specific slots this instructor is unavailable for on this date. Empty means the whole date.', related_name='instructor_leaves', to='classes_app.slot')),
            ],
            options={
                'db_table': 'instructors_instructor_leave',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['instructor', 'date'], name='idx_instrleave_instr_date')],
            },
        ),
    ]
