# Generated by Django 5.1.15 on 2026-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_photos/'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
