# Generated by Django 5.1.15 on 2026-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructorprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
