# Generated by Django 5.1.15 on 2026-08-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructorprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
