# Generated by Django 5.1.15 on 2026-07-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('start_time', models.TimeField(help_text='Working start time, e.g. 09:00.')),
                ('end_time', models.TimeField(help_text='Working end time, e.g. 21:00.')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(help_text='Length of each generated slot, in minutes.')),
            ],
            options={
                'db_table': 'classes_timetable_config',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_booked', models.BooleanField(default=False)),
                ('source_config', models.ForeignKey(help_text='The TimetableConfig row this slot was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='classes_app.timetableconfig')),
            ],
            options={
                'db_table': 'classes_slot',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='idx_slot_date'), models.Index(fields=['date', 'is_booked'], name='idx_slot_date_booked')],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time'), name='unique_slot_per_date_start_time')],
            },
        ),
    ]
