from datetime import time

from django.db import migrations


DEFAULT_START = time(9, 0)
DEFAULT_END = time(21, 0)
DEFAULT_DURATION_MINUTES = 60


def seed_timetable_config(apps, schema_editor):
    TimetableConfig = apps.get_model('classes_app', 'TimetableConfig')

    for weekday in range(7):
        TimetableConfig.objects.get_or_create(
            weekday=weekday,
            defaults={
                'is_open': True,
                'start_time': DEFAULT_START,
                'end_time': DEFAULT_END,
                'slot_duration_minutes': DEFAULT_DURATION_MINUTES,
            },
        )

    # Initial slots are generated by 0004, after the Leave table exists.
    # Keeping this migration limited to timetable rows makes the migration
    # dependency order safe for a fresh database.


def unseed_timetable_config(apps, schema_editor):
    TimetableConfig = apps.get_model('classes_app', 'TimetableConfig')
    TimetableConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
        # The core dependency is retained because timetable generation uses
        # StudioSetting after this seed migration completes.
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_timetable_config, unseed_timetable_config),
    ]
