# Generated by Django 5.1.15 on 2026-07-31 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0002_seed_timetable_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes_leave',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='leave',
            field=models.ForeignKey(blank=True, help_text='Set when this slot falls within an active leave period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to='classes_app.leave'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['leave'], name='idx_slot_leave'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_leave_date_range'),
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_date_gte_start_date'),
        ),
    ]
