# Generated by Django 5.1.15 on 2026-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0004_generate_initial_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconfig',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='End of the daily rest/break window (optional).', null=True),
        ),
        migrations.AddField(
            model_name='timetableconfig',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Start of the daily rest/break window (optional). No slots are generated inside it.', null=True),
        ),
    ]
