# Generated by Django 5.1.15 on 2026-08-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_timetableconfig_break_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slot',
            name='idx_slot_date_booked',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AlterField(
            model_name='slot',
            name='leave',
            field=models.ForeignKey(blank=True, help_text='Set when this slot falls within an active studio-wide leave period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to='classes_app.leave'),
        ),
    ]
