# Generated by Django 5.1.15 on 2026-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'created_at'], name='idx_user_active_date'),
        ),
    ]
