# Generated by Django 5.1.15 on 2026-08-05 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_admin_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    AdminProfile = apps.get_model('accounts', 'AdminProfile')

    for user in User.objects.filter(role='admin'):
        AdminProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_age_emailchangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_admin_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_admin_profiles, migrations.RunPython.noop),
    ]
