# Generated by Django 5.1.15 on 2026-08-09 03:33

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(default=apps.accounts.models._generate_otp, max_length=6)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models._registration_otp_expiry)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_registration_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
