# Generated by Django 5.1.15 on 2026-09-19 10:11

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registrationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(default=apps.accounts.models._generate_otp, max_length=6),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=apps.accounts.models._otp_expiry),
        ),
    ]
