# Generated by Django 5.1.15 on 2026-07-31 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_sessions', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether new purchases/renewals are currently allowed against this plan.')),
            ],
            options={
                'db_table': 'payments_subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='SlotPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Snapshot of the single-slot price at purchase time.', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_slot_purchase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('exhausted', 'Sessions Exhausted'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('sessions_included', models.PositiveIntegerField(help_text='Snapshot of plan.included_sessions at purchase/renewal time.')),
                ('sessions_remaining', models.PositiveIntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Snapshot of plan.monthly_price at purchase/renewal time.', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan', models.ForeignKey(help_text='The plan configuration in effect when this subscription was purchased/renewed.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_user_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_usersub_user_status')],
            },
        ),
    ]
