# Generated by Django 5.1.15 on 2026-08-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_cancelled_at_alter_booking_status_and_more'),
        ('payments', '0005_payment_currency_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotpurchase',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Set when this credit is consumed by a booking.', null=True),
        ),
        migrations.AddField(
            model_name='slotpurchase',
            name='used_for_booking',
            field=models.ForeignKey(blank=True, help_text='The booking this credit was spent on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_purchase_credits_used', to='bookings.booking'),
        ),
    ]
