# Generated by Django 5.1.15 on 2026-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_slotpurchase_used_at_slotpurchase_used_for_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='low_usage_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set once the 10-days-left low-usage reminder email has been sent for this cycle, so it never sends twice.', null=True),
        ),
    ]
