# Generated by Django 5.1.15 on 2026-08-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_usersubscription_low_usage_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('exhausted', 'Sessions Exhausted'), ('cancelled', 'Cancelled')], default='active', max_length=16),
        ),
    ]
